/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/patient-home`; params?: Router.UnknownInputParams; } | { pathname: `/patient-not-sure`; params?: Router.UnknownInputParams; } | { pathname: `/patient-recognize`; params?: Router.UnknownInputParams; } | { pathname: `/patient-result`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/caregiver/activity-log`; params?: Router.UnknownInputParams; } | { pathname: `/caregiver/add-patient`; params?: Router.UnknownInputParams; } | { pathname: `/caregiver/add-person`; params?: Router.UnknownInputParams; } | { pathname: `/caregiver/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/caregiver/manage-people`; params?: Router.UnknownInputParams; } | { pathname: `/caregiver/person-details`; params?: Router.UnknownInputParams; } | { pathname: `/caregiver/preferences`; params?: Router.UnknownInputParams; } | { pathname: `/caregiver/voice-sample`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/patient-home`; params?: Router.UnknownOutputParams; } | { pathname: `/patient-not-sure`; params?: Router.UnknownOutputParams; } | { pathname: `/patient-recognize`; params?: Router.UnknownOutputParams; } | { pathname: `/patient-result`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/caregiver/activity-log`; params?: Router.UnknownOutputParams; } | { pathname: `/caregiver/add-patient`; params?: Router.UnknownOutputParams; } | { pathname: `/caregiver/add-person`; params?: Router.UnknownOutputParams; } | { pathname: `/caregiver/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/caregiver/manage-people`; params?: Router.UnknownOutputParams; } | { pathname: `/caregiver/person-details`; params?: Router.UnknownOutputParams; } | { pathname: `/caregiver/preferences`; params?: Router.UnknownOutputParams; } | { pathname: `/caregiver/voice-sample`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/patient-home${`?${string}` | `#${string}` | ''}` | `/patient-not-sure${`?${string}` | `#${string}` | ''}` | `/patient-recognize${`?${string}` | `#${string}` | ''}` | `/patient-result${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/caregiver/activity-log${`?${string}` | `#${string}` | ''}` | `/caregiver/add-patient${`?${string}` | `#${string}` | ''}` | `/caregiver/add-person${`?${string}` | `#${string}` | ''}` | `/caregiver/dashboard${`?${string}` | `#${string}` | ''}` | `/caregiver/manage-people${`?${string}` | `#${string}` | ''}` | `/caregiver/person-details${`?${string}` | `#${string}` | ''}` | `/caregiver/preferences${`?${string}` | `#${string}` | ''}` | `/caregiver/voice-sample${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/patient-home`; params?: Router.UnknownInputParams; } | { pathname: `/patient-not-sure`; params?: Router.UnknownInputParams; } | { pathname: `/patient-recognize`; params?: Router.UnknownInputParams; } | { pathname: `/patient-result`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/caregiver/activity-log`; params?: Router.UnknownInputParams; } | { pathname: `/caregiver/add-patient`; params?: Router.UnknownInputParams; } | { pathname: `/caregiver/add-person`; params?: Router.UnknownInputParams; } | { pathname: `/caregiver/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/caregiver/manage-people`; params?: Router.UnknownInputParams; } | { pathname: `/caregiver/person-details`; params?: Router.UnknownInputParams; } | { pathname: `/caregiver/preferences`; params?: Router.UnknownInputParams; } | { pathname: `/caregiver/voice-sample`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
